# Creating Numpy Arrays

In [1]:
import numpy as np

In [2]:
#1D array also called as vectors
a = np.array([1,2,3])
print(a)

[1 2 3]


In [3]:
# 2D array also called as metrics 
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [4]:
# 3D array also called as Tensors

c = np.array([[[1,2],[0,4],[5,6]]])
print(c)

[[[1 2]
  [0 4]
  [5 6]]]


In [5]:
# changing dtype 
d = np.array([[[1,2],[0,4],[5,6]]], dtype=bool)
print(d)

[[[ True  True]
  [False  True]
  [ True  True]]]


In [6]:
# arange func works same as python range function

np.arange(1,13)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [7]:
# reshape func used to reshape the array

np.arange(1,21).reshape(4,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [8]:
# tuples are provided inside the function
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [9]:
# np.zeros is similar as np.ones method
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [10]:
# random.randint func generates random numbers

np.random.randint(1,6)

5

In [11]:
# random.random generates random arrays
np.random.random((4,5))

array([[0.3112385 , 0.75157704, 0.92348958, 0.02743602, 0.04844593],
       [0.62373326, 0.75155442, 0.98971249, 0.89348804, 0.66365566],
       [0.38761525, 0.47817541, 0.99272019, 0.64710941, 0.25626053],
       [0.79772332, 0.58818001, 0.77399324, 0.3118026 , 0.94939544]])

In [12]:
# linearly seprable  function used to seprate function with equal distance
np.linspace(10,50,10)

array([10.        , 14.44444444, 18.88888889, 23.33333333, 27.77777778,
       32.22222222, 36.66666667, 41.11111111, 45.55555556, 50.        ])

In [13]:
np.linspace(-10,10,10)

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [14]:
# in identity function diagnol items are 1
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

# Numpy Attributes

In [15]:
# ndim : no of dimensions

a = np.arange(16).reshape(2,2,2,2)
a.ndim

4

In [16]:
# shape 
a.shape

(2, 2, 2, 2)

In [17]:
a1 = np.array([[[1,2],[1,3],[4,5]]],dtype=np.int64)
print(a1.shape)
a1

(1, 3, 2)


array([[[1, 2],
        [1, 3],
        [4, 5]]], dtype=int64)

In [18]:
a1.size

6

In [19]:
a1.itemsize

8

In [20]:
a1.dtype

dtype('int64')

# Changing Datatype

In [21]:
# astype function used for changing datatype of the readily available numpy array
a2 = np.array([[[1,2],[3,4],[5,6]]])
a2 = a2.astype('int64')
a2.dtype

dtype('int64')

# Array Operations

In [22]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

In [23]:
a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [24]:
a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

Scaler Operations : Arithmetic

In [25]:
# Addition
scaler = 2
result = a2 + 2
result

array([[14, 15, 16, 17],
       [18, 19, 20, 21],
       [22, 23, 24, 25]])

In [26]:
# Multiplications
scaler = 2
result = a2 * scaler
result


array([[24, 26, 28, 30],
       [32, 34, 36, 38],
       [40, 42, 44, 46]])

In [27]:
# substractions
scaler = 1
result = a1 - scaler
result

array([[-1,  0,  1,  2],
       [ 3,  4,  5,  6],
       [ 7,  8,  9, 10]])

In [28]:
# Division
scaler = 12
result = a2 / scaler
result

array([[1.        , 1.08333333, 1.16666667, 1.25      ],
       [1.33333333, 1.41666667, 1.5       , 1.58333333],
       [1.66666667, 1.75      , 1.83333333, 1.91666667]])

In [29]:
# Exponential
scaler = 2
result = a1 **scaler
result

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [30]:
# Remainder
scaler = 3
result = a1 % scaler
result

array([[0, 1, 2, 0],
       [1, 2, 0, 1],
       [2, 0, 1, 2]], dtype=int32)

Scaler Operations : Relational

In [31]:
a2>18

array([[False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True]])

In [32]:
a2 ==  a1

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [33]:
a2!=a1

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [34]:
a1<a2

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

Vector Operations

In [35]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])


In [36]:
arr1 + arr2

array([5, 7, 9])

In [37]:
arr1 * arr2

# hence you can perform all arithmetic operations on array of same shape

array([ 4, 10, 18])

Mathematical Operations

In [38]:
arr1 = np.arange(12).reshape(3,4)
arr2 = np.arange(12,24).reshape(3,4)

In [39]:
arr1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [40]:
arr2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [41]:
# Min
np.min(arr2)

12

In [42]:
# Max
np.max(arr2,axis = 0) # you can also change row = 1 and columns = 0

array([20, 21, 22, 23])

In [43]:
# sum
np.sum(arr1,axis = 0)

array([12, 15, 18, 21])

In [44]:
# product 
np.prod(arr1,axis = 1)

array([   0,  840, 7920])

Statistical Operations

In [45]:
#Mean 
np.mean(arr1)

5.5

In [46]:
# Median
np.median(arr1,axis = 1)

array([1.5, 5.5, 9.5])

In [47]:
# variance
np.var(arr1)

11.916666666666666

In [48]:
# standard deviation
np.std(arr1)

3.452052529534663

In [49]:
# log
np.log(arr2)

array([[2.48490665, 2.56494936, 2.63905733, 2.7080502 ],
       [2.77258872, 2.83321334, 2.89037176, 2.94443898],
       [2.99573227, 3.04452244, 3.09104245, 3.13549422]])

In [50]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(4,3)

In [51]:
a2

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [52]:
a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [53]:
# Dot product of two array
np.dot(a1,a2)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [54]:
# exponential
np.exp(a1)

array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03],
       [2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04]])

In [55]:
np.round(np.random.random((3,4))*100)

array([[55., 74.,  5., 77.],
       [14., 26.,  4., 49.],
       [25., 50., 49., 57.]])

# Indexing & Slicing

In [56]:
a1 = np.arange(12)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

In [57]:
a1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [58]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [59]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

# indexing


In [60]:
a4 = np.arange(16).reshape(2,2,2,2)
a4

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]]])

In [65]:
a4[1,1,1,1]

15

In [66]:
b1 = np.arange(12).reshape(3,4)

In [67]:
b1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [72]:
b1[1:,2:]

array([[ 6,  7],
       [10, 11]])

In [74]:
b2 = np.arange(12)
b2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [82]:
b2[2::2]

array([ 2,  4,  6,  8, 10])

In [91]:
b1[1:,1:]

array([[ 5,  6,  7],
       [ 9, 10, 11]])

In [99]:
b1[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [100]:
b1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [105]:
b1[::2,::3]

array([[ 0,  3],
       [ 8, 11]])

In [115]:
b1[0::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [122]:
b1[0:2,1:]

array([[1, 2, 3],
       [5, 6, 7]])

In [124]:
b3 = np.arange(27).reshape(3,3,3)
b3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [136]:
b3[1,0::2,0::2]

array([[ 9, 11],
       [15, 17]])

# Transpose
 converts opposite like rows into columns and columns into rows

In [137]:
b3  

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [139]:
np.transpose(b3)

array([[[ 0,  9, 18],
        [ 3, 12, 21],
        [ 6, 15, 24]],

       [[ 1, 10, 19],
        [ 4, 13, 22],
        [ 7, 16, 25]],

       [[ 2, 11, 20],
        [ 5, 14, 23],
        [ 8, 17, 26]]])

# Ravel
converts any array into 1D array

In [140]:
np.ravel(b3)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

# Stacking 
  1.Horizontal Stack 
  2.Vertical Stack

In [146]:
g1 = np.arange(12).reshape(3,4)
g2 = np.arange(12).reshape(3,4)
g1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [150]:
np.hstack((g1,g2))

array([[ 0,  1,  2,  3,  0,  1,  2,  3],
       [ 4,  5,  6,  7,  4,  5,  6,  7],
       [ 8,  9, 10, 11,  8,  9, 10, 11]])

In [149]:
np.vstack((g1,g2))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [151]:
b3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

Horizontal split

In [158]:
np.hsplit(b3,3)

[array([[[ 0,  1,  2]],
 
        [[ 9, 10, 11]],
 
        [[18, 19, 20]]]),
 array([[[ 3,  4,  5]],
 
        [[12, 13, 14]],
 
        [[21, 22, 23]]]),
 array([[[ 6,  7,  8]],
 
        [[15, 16, 17]],
 
        [[24, 25, 26]]])]

Vertical Split

In [159]:
np.vsplit(b3,3)

[array([[[0, 1, 2],
         [3, 4, 5],
         [6, 7, 8]]]),
 array([[[ 9, 10, 11],
         [12, 13, 14],
         [15, 16, 17]]]),
 array([[[18, 19, 20],
         [21, 22, 23],
         [24, 25, 26]]])]