In [1]:
import numpy as np

In [3]:
a = np.arange(1,17).reshape(4,4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

# Sorting

In [4]:
a.sort()

In [5]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [6]:
b = np.random.randint(1,67,16).reshape(4,4)
b

array([[ 2, 32, 33,  6],
       [42, 66, 29, 62],
       [37, 26, 15, 18],
       [61, 25, 39, 16]])

In [17]:
b.ndim

2

In [8]:
b.sort()
b

array([[ 2,  6, 32, 33],
       [29, 42, 62, 66],
       [15, 18, 26, 37],
       [16, 25, 39, 61]])

# Concatenate

In [10]:
np.concatenate((a,b))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [ 2,  6, 32, 33],
       [29, 42, 62, 66],
       [15, 18, 26, 37],
       [16, 25, 39, 61]])

# Unique

In [12]:
c = np.array([[1,2,3],[3,4,5],[3,4,6]])
c

array([[1, 2, 3],
       [3, 4, 5],
       [3, 4, 6]])

In [13]:
np.unique(c)

array([1, 2, 3, 4, 5, 6])

In [14]:
c.ndim

2